name: Linting

on:
  push:
    branches:
      - "*"
    paths:
      - '**/*.php'
      - 'composer.json'
      - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - "master"
    paths:
      - '**.js*'
      - '**.ts*'
      - 'package*.json'
      - '.github/workflows/lint.yml'
env:
  APP_ENV: development

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4']

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: phpcs

      - name: Run soft linting
        if: github.event_name == 'push'
        uses: wearerequired/lint-action@v1
        env:
          APP_ENV: ${{ env.APP_ENV }}
        with:
          auto_fix: false
          php_codesniffer: true
          # Optional: Ignore warnings
          php_codesniffer_args: "--standard=PSR12 -n"

      - name: Run hard linting
        if: github.event_name == 'pull_request'
        uses: wearerequired/lint-action@v1
        env:
          APP_ENV: ${{ env.APP_ENV }}
        with:
          continue_on_error: false
          php_codesniffer: true
          # Optional: Ignore warnings
          php_codesniffer_args: "--standard=PSR12"
